kind: Secret
apiVersion: v1
metadata:
  name: beatwave-backend-mongo-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password123@beatwave-mongodb:27017/beatwave_db?authSource=admin"
