kind: Secret
apiVersion: v1
metadata:
  name: beatwave-backend-secrets
type: Opaque
stringData:
  CLERK_SECRET_KEY: "sk_test_Adw0KTRW2iPCapS5CLH7lp11jD4smATfy03RZzXkRO"
  CLERK_PUBLISHABLE_KEY: "pk_test_b25lLXRyb2xsLTcuY2xlcmsuYWNjb3VudHMuZGV2JA"
  R2_ACCESS_KEY_ID: "d32c05a8cf9e10c9a5f9c926ee25016a"
  R2_SECRET_ACCESS_KEY: "4413ca96394cae214a968d958662c020f28ef750be3416488da2de6bf3956dfb"
  R2_ACCOUNT_ID: "d80940774294305ead9478c166f3f74b"
  R2_BUCKET_NAME: "beatwave-bucket"
  R2_PUBLIC_URL: "https://pub-9414df13a4124b6796e9532dd94f4ab8.r2.dev"
  MONGODB_URI: "mongodb://admin:password123@beatwave-mongodb:27017/beatwave_db?authSource=admin"
  RAZORPAY_KEY_ID: "rzp_test_zOhpl2KPINrq20"
  RAZORPAY_KEY_SECRET: "05kRpC9bdgvFeZIqURA62jXz"
  CLOUDINARY_API_KEY: "183376254914523"
  CLOUDINARY_API_SECRET: "I_390-QsdGBlVnJb0B30qz-ywY0"
  CLOUDINARY_CLOUD_NAME: "dxevfrvvd"