kind: Deployment
apiVersion: apps/v1
metadata:
  name: beatwave-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beatwave-frontend
  template:
    metadata:
      labels:
        app: beatwave-frontend
    spec:
      containers:
        - name: beatwave-frontend
          image: ghcr.io/kunal-511/beatwave:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: beatwave-frontend-config