kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: beatwave
namespace: beatwave
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secrets.yaml
  - ../external-secrets/cluster-secret-store.yaml
  - ../external-secrets/backend-external-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - mongodb-statefulset.yaml
  - mongodb-service.yaml
  - mongodb-secrets.yaml