apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beatwave-mongodb
  namespace: beatwave
spec:
  serviceName: beatwave-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: beatwave-mongodb
  template:
    metadata:
      labels:
        app: beatwave-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongodb
          envFrom:
            - secretRef:
                name: beatwave-mongodb-secrets
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /data/configdb
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: mongodb-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

