kind: Secret
apiVersion: v1
metadata:
  name: beatwave-mongodb-secrets
  namespace: beatwave
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password123"
  MONGO_INITDB_DATABASE: "beatwave_db"