# values.yaml
namespace: beatwave

backend:
  name: backend
  replicaCount: 1
  image:
    repository: ghcr.io/kunal-511/beatwave-backend
    tag: v2
    pullPolicy: IfNotPresent
  port: 5000
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: ghcr.io/kunal-511/beatwave
    tag: v2
    pullPolicy: IfNotPresent
  port: 3000
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

configMap:
  PORT: "5000"
  ADMIN_EMAIL: "yoyokvunal@gmail.com"
  NODE_ENV: "development"

secrets:
  VITE_CLERK_PUBLISHABLE_KEY: "pk_test_b25lLXRyb2xsLTcuY2xlcmsuYWNjb3VudHMuZGV2JA"
  CLERK_SECRET_KEY: "sk_test_Adw0KTRW2iPCapS5CLH7lp11jD4smATfy03RZzXkRO"
  CLOUDINARY_API_KEY: "183376254914523"
  CLOUDINARY_API_SECRET: "I_390-QsdGBlVnJb0B30qz-ywY0"
  CLOUDINARY_CLOUD_NAME: "dxevfrvvd"
  MONGODB_URI: "mongodb+srv://yoyokvunal:SflISJ3jlvg5c0JQ@cluster0.nws3o.mongodb.net/beatwave_db?retryWrites=true&w=majority&appName=Cluster0"

ingress:
  enabled: true
  hostname: beatwave.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  paths:
    - path: /
      pathType: Prefix
      serviceName: frontend
      servicePort: 3000
    - path: /api
      pathType: Prefix
      serviceName: backend
      servicePort: 5000

# Test Connection parameters
testConnection:
  enabled: true
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  # Which service to test; can be "frontend" or "backend"
  target: frontend
  command: ["wget"]
  args:
    - "-qO-"
    - "http://$(TARGET_SERVICE):$(TARGET_PORT)/"
  timeoutSeconds: 60