apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatwave-backend
  labels:
    environment: production
    tier: backend
spec:
  template:
    metadata:
      labels:
        environment: production
        tier: backend
