kind: Secret
apiVersion: v1
metadata:
  name: beatwave-backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://yoyokvunal:SflISJ3jlvg5c0JQ@cluster0.nws3o.mongodb.net/beatwave_db?retryWrites=true&w=majority&appName=Cluster0"
  