apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatwave-backend
spec:
  template:
    spec:
      containers:
        - name: beatwave-backend
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
