apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatwave-frontend
  labels:
    environment: production
    tier: frontend
spec:
  template:
    metadata:
      labels:
        environment: production
        tier: frontend
