kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: beatwave-production
namespace: beatwave-production
resources:
  - ../base
  - backend-hpa.yaml
  - frontend-hpa.yaml
  - redis-hpa.yaml
patches:
  - path: backend-labels.yaml
  - path: frontend-labels.yaml
  - path: redis-labels.yaml
  - path: backend-resources.yaml
  - path: frontend-resources.yaml
  - path: redis-resources.yaml
  - path: backend-secrets.yaml