apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatwave-frontend-deployment
  namespace: beatwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: beatwave-frontend-pod
      namespace: beatwave
      labels:
        app: frontend
    spec:
      containers:
      - name: beatwave-frontend
        image: ghcr.io/kunal-511/beatwave:v0.0.1
        ports:
        - containerPort: 80
        env:
        - name: VITE_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: VITE_CLERK_PUBLISHABLE_KEY
        
        - name: VITE_API_URL
          value: "http://backend:5000/api"
