apiVersion: v1
kind: Secret
metadata:
  name: beatwave-{{ .Values.backend.name }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "beatwave.labels" . | nindent 4 }}
    app: beatwave-{{ .Values.backend.name }}
type: Opaque
stringData:
  CLERK_SECRET_KEY: {{ .Values.backend.secrets.clerkSecretKey | quote }}
  CLERK_PUBLISHABLE_KEY: {{ .Values.backend.secrets.clerkPublishableKey | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.backend.secrets.r2AccessKeyId | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.backend.secrets.r2SecretAccessKey | quote }}
  R2_ACCOUNT_ID: {{ .Values.backend.secrets.r2AccountId | quote }}
  R2_BUCKET_NAME: {{ .Values.backend.secrets.r2BucketName | quote }}
  R2_PUBLIC_URL: {{ .Values.backend.secrets.r2PublicUrl | quote }}
  MONGODB_URI: {{ .Values.backend.secrets.mongodbUri | quote }}
  RAZORPAY_KEY_ID: {{ .Values.backend.secrets.razorpayKeyId | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.backend.secrets.razorpayKeySecret | quote }}
  CLOUDINARY_API_KEY: {{ .Values.backend.secrets.cloudinaryApiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.backend.secrets.cloudinaryApiSecret | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.backend.secrets.cloudinaryCloudName | quote }}

