apiVersion: v1
kind: Service
metadata:
  name: beatwave-{{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "beatwave.labels" . | nindent 4 }}
    app: beatwave-{{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: beatwave-{{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}

