{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beatwave-{{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "beatwave.labels" . | nindent 4 }}
    app: beatwave-{{ .Values.mongodb.name }}
spec:
  serviceName: beatwave-{{ .Values.mongodb.name }}
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: beatwave-{{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: beatwave-{{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.rootUsername | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.auth.rootPassword | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.auth.database | quote }}
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /data/configdb
          {{- end }}
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: 
          - {{ .Values.mongodb.persistence.data.accessMode }}
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.data.size }}
    - metadata:
        name: mongodb-config
      spec:
        accessModes: 
          - {{ .Values.mongodb.persistence.config.accessMode }}
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.config.size }}
  {{- end }}
{{- end }}

