# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  VITE_CLERK_PUBLISHABLE_KEY: {{ .Values.secrets.VITE_CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: {{ .Values.secrets.CLERK_SECRET_KEY }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.CLOUDINARY_API_KEY | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.CLOUDINARY_API_SECRET }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.CLOUDINARY_CLOUD_NAME }}
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}