apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beatwave-backend-external-secrets
  namespace: beatwave
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: beatwave-backend-secrets
    creationPolicy: Merge

  data:
    - secretKey: CLERK_SECRET_KEY
      remoteRef:
        key: /beatwave/CLERK_SECRET_KEY

    - secretKey: CLERK_PUBLISHABLE_KEY
      remoteRef:
        key: /beatwave/CLERK_PUBLISHABLE_KEY

    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: /beatwave/R2_ACCESS_KEY_ID

    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: /beatwave/R2_SECRET_ACCESS_KEY

    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: /beatwave/R2_ACCOUNT_ID

    - secretKey: R2_BUCKET_NAME
      remoteRef:
        key: /beatwave/R2_BUCKET_NAME

    - secretKey: R2_PUBLIC_URL
      remoteRef:
        key: /beatwave/R2_PUBLIC_URL

    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: /beatwave/RAZORPAY_KEY_ID

    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: /beatwave/RAZORPAY_KEY_SECRET
